CREATE TABLE PC_PARTS(PC_PARTS_PK INT PRIMARY KEY, PC_PARTS_TITLE VARCHAR(30), PC_PARTS_CODE INT, PC_PARTS_MAKER VARCHAR(30), PC_PARTS_AVAIL INT, PC_PARTS_DESC VARCHAR(100));
INSERT INTO PC_PARTS VALUES(1, 'Intel MB', 123456789, 'Intel', 5, 'Intel motherboard');
INSERT INTO PC_PARTS VALUES(2, 'AMD MB', 987654321, 'AMD', 3, 'AMD motherboard');
INSERT INTO PC_PARTS VALUES(3, 'HP Laptop', 123456, 'HP', 5, 'HP Laptop with 15 inch screen');
INSERT INTO PC_PARTS VALUES(4, 'IBM Desktop', 123457, 'IBM', 10, 'IBM Desktop');
INSERT INTO PC_PARTS VALUES(5, 'Dell Desktop', 123458, 'DELL', 14, 'Dell Desktop');
INSERT INTO PC_PARTS VALUES(6, 'HP Desktop', 123459, 'HP', 3, 'HP Desktop');